spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: cursoms-eureka-user
      password: teste123

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
