spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/mscourserealm

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://cursoms-eureka-user:teste123@localhost:8761/eureka
